name: Fetch Compliance News

on:
  schedule:
    - cron: '0 * * * *'   # hourly
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        working-directory: scripts
        run: npm install

      - name: Fetch news and summarize
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # optional
          OPENAI_MODEL: gpt-4o-mini
          DAYS_BACK: '14'
          MAX_ITEMS_PER_FEED: '30'
          SUMMARIZE_LIMIT: '60'
        run: node scripts/fetch.mjs

      - name: Commit & push updated news.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else:
            git commit -m "chore: update news.json [skip ci]"
            git push
          fi
